[package]
name = "roguelike"
version = "0.1.0"
authors = ["Charlie Boggus <charlie.boggus@gmail.com>"]
edition = "2018"

[dependencies]
tcod = { version = "0.14.0", features = ["serialization"] }
rand = "0.6.5"
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"